spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photos?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  thymeleaf:
    cache: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    excluded-view-names:
    template-resolver-order:
  #session存储方式
  session:
    store-type: none

server:
  port: 80

#照片上传地址(需要手动创建目录)
custom:
    savePath: E://uploadPhotos//

#日志相关配置
logging:
  level: info
  file: E://logs//photos.log
